### PR TITLE
[libarchive] Update to 3.5.2. JB#55589

### PR DESCRIPTION
**Pull request by pvuorela**
@mkenttala @Tomin1 @spiiroin

### CODE REVIEW

**Review by Tomin1 — COMMENTED** [review]
Looks fine but there are some obsolete things in the spec file: make uses jobs macro, urls are not quite up to date (URL, Source0) and the subpackages have Group tags. [EDIT: And I guess URL should anyway point to this repo, Source0 shouldn't have any url]

**Comment by pvuorela** [comment]
On packaging upstream projects the url is quite often the upstream url, and that might serve the purpose better too. Changed the source now.

**Comment by Tomin1** [comment]
> On packaging upstream projects the url is quite often the upstream url, and that might serve the purpose better too. Changed the source now.

Well, sort of (*), but more importantly that url has also changed. If you open it, you see that message "libarchive has Moved!". There is also new url for it there. I think it's been a while since Google Code was shut down.

(*) https://docs.sailfishos.org/Reference/Software_Packaging/#recent-changes-in-sailfish-os-packaging

**Comment by pvuorela** [comment]
The google code shutdown is indeed quite a good reason to move :D Just switched now to this repo, should be good enough too.

**Review by spiiroin — APPROVED** [review]

**Pull request merged**
